Argument parsing
bonlang/bonc pull request #9
Opened 2021-05-19 15:03 UTC by miffi

2021-05-19 17:03 UTC, wooosh commented
closes #6

2021-05-19 18:41 UTC, garfr requested changes
This is a great improvement over the previous argument and it should make adding more complicated features much easier.

2021-05-19 18:41 UTC, garfr commented on src/args.c
> +short_flag_parse(const char *flag, char *next_argv, struct Option *opts[],
This parser does not check to ensure the length of the args is the same, so the flag ``-vNONSENSE`` will be equivalent to ``-v``

2021-05-19 18:41 UTC, garfr commented on src/args.c
> +long_flag_parse(const char *flag, struct Option *opts[], size_t opts_length) {
This also doesn't check for the difference between ``--dump-ast`` and ``--dump-ast-NONSENSE``.

2021-05-19 18:41 UTC, garfr commented on src/args.c
> +    if (argv[i][0] == '-') {
This may cause problems if the string literal ``""`` or ``-`` is passed as an argument.

2021-05-19 18:41 UTC, garfr commented on src/bcc2.c
> +                           &list_platforms};
It may be worth it to make this array NULL terminated instead of computing its size with integer division.

2021-05-20 12:27 UTC, garfr approved these changes

2021-05-20 12:28 UTC, merged